'use client';

import Link from 'next/link';
import BrandLogo from '@/components/brand/BrandLogo';
import { branding, copyrightLine, hasPublicContact } from '@/config/branding';

export default function Footer() {
  return <footer className="mt-auto border-t border-slate-700 bg-[#0b132b] text-slate-200"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 sm:grid-cols-2 sm:px-6 lg:grid-cols-4 lg:px-8"><div><BrandLogo theme="light" href="/" height={30} /><p className="mt-4 max-w-xs text-sm leading-6 text-slate-300">{branding.shortDescription}</p></div><div><h2 className="text-sm font-bold text-white">Shop</h2><ul className="mt-3 space-y-2 text-sm"><li><Link href="/products" className="hover:text-white">All products</Link></li><li><Link href="/wishlist" className="hover:text-white">Wishlist</Link></li><li><Link href="/cart" className="hover:text-white">Cart</Link></li></ul></div><div><h2 className="text-sm font-bold text-white">Your account</h2><ul className="mt-3 space-y-2 text-sm"><li><Link href="/account" className="hover:text-white">Account</Link></li><li><Link href="/orders" className="hover:text-white">Orders and tracking</Link></li><li><Link href="/account#returns" className="hover:text-white">Returns and refunds</Link></li></ul></div><div><h2 className="text-sm font-bold text-white">Support</h2><p className="mt-3 text-sm leading-6 text-slate-300">Delivery and payment availability are confirmed from current market configuration during checkout.</p>{hasPublicContact(branding.supportEmail) && <a href={`mailto:${branding.supportEmail}`} className="mt-3 block text-sm font-semibold text-[#ffb45a] hover:text-white">Contact support</a>}</div></div><div className="border-t border-slate-700 px-4 py-5 text-center text-xs text-slate-400">{copyrightLine()}</div></footer>;
}
