'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { Heart, ShoppingCart, Trash2 } from 'lucide-react';
import { useCartStore, type WishlistItem } from '@/store/cartStore';
import { useAuthStore } from '@/store/authStore';
import { accountService } from '@/services/account.service';

type RemoteItem = { id: string; product: { _id: string; name: string; slug?: string; price: number; salePrice?: number; images?: string[]; stock?: number } };
export default function WishlistPage() {
  const { wishlist: localItems, removeFromWishlist: removeLocal, moveWishlistToCart, addToCart } = useCartStore();
  const { isAuthenticated } = useAuthStore();
  const [items, setItems] = useState<RemoteItem[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { if (!isAuthenticated) return; setLoading(true); setError(''); try { const result = await accountService.wishlist(); setItems(result.items as RemoteItem[]); } catch { setError('Saved products could not be loaded. Please try again.'); } finally { setLoading(false); } }, [isAuthenticated]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const remove = async (item: RemoteItem | WishlistItem) => { if (isAuthenticated && 'product' in item) { await accountService.removeWishlist(item.product._id); await load(); } else removeLocal(item.id); };
  const display = isAuthenticated ? items : localItems;
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-sm font-semibold text-[#ff8a00]">SAVED PRODUCTS</p><h1 className="mt-1 text-3xl font-bold text-[#0b132b]">Your wishlist</h1><p className="mt-2 text-sm text-slate-600">{isAuthenticated ? 'Saved to your account and available across your signed-in devices.' : 'This temporary wishlist is saved in this browser. Sign in to keep it with your account.'}</p>{error && <div role="alert" className="mt-5 border border-amber-300 bg-amber-50 p-4 text-sm"><p>{error}</p><button type="button" onClick={() => void load()} className="mt-2 font-semibold underline">Retry</button></div>}{loading ? <div className="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-52 animate-pulse bg-slate-200" />)}</div> : display.length === 0 ? <section className="mt-6 border border-dashed border-slate-300 bg-white p-10 text-center"><Heart className="mx-auto text-[#ff8a00]" /><h2 className="mt-3 font-semibold">Nothing saved yet</h2><p className="mt-1 text-sm text-slate-600">Save available products to return to them later.</p><Link href="/products" className="mt-5 inline-block rounded-md bg-[#0b132b] px-4 py-2 text-sm font-semibold text-white">Browse products</Link></section> : <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{display.map((item) => { const remote = 'product' in item ? item.product : null; const local = item as WishlistItem; const id = remote ? remote._id : local.id; const name = remote ? remote.name : local.name; const price = Number(remote ? remote.salePrice ?? remote.price : local.price); const available = remote ? Number(remote.stock ?? 0) > 0 : true; return <article key={'product' in item ? item.id : local.id} className="border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-4"><div><Link href={`/products/${id}`} className="font-semibold text-[#0b132b] hover:underline">{name}</Link><p className="mt-2 text-sm font-bold">PKR {price.toLocaleString()}</p><p className={`mt-1 text-xs font-medium ${available ? 'text-emerald-700' : 'text-slate-500'}`}>{available ? 'Available to order' : 'Currently unavailable'}</p></div><Heart className="text-[#ff8a00]" /></div><div className="mt-5 flex gap-3"><button type="button" disabled={!available} onClick={() => { if (remote) addToCart({ id, name, price, image: remote.images?.[0] || '', stock: remote.stock }); else moveWishlistToCart(local.id); }} className="inline-flex items-center gap-2 rounded-md bg-[#0b132b] px-3 py-2 text-sm font-semibold text-white disabled:opacity-50"><ShoppingCart size={16} /> Add to cart</button><button type="button" onClick={() => void remove(item)} className="inline-flex items-center gap-1 text-sm font-semibold text-slate-600 hover:text-red-700"><Trash2 size={16} /> Remove</button></div></article>; })}</section>}</main>;
}
