module.exports = {
  AUTH: {
    LOGIN_SUCCESS: 'AUTH.LOGIN.SUCCESS',
    LOGIN_FAILED: 'AUTH.LOGIN.FAILED',
    LOGOUT: 'AUTH.LOGOUT',
    REGISTER: 'AUTH.REGISTER',
    PASSWORD_RESET: 'AUTH.PASSWORD.RESET',
    PASSWORD_CHANGED: 'AUTH.PASSWORD.CHANGED',
    EMAIL_VERIFIED: 'AUTH.EMAIL.VERIFIED',
    SESSION_CREATED: 'AUTH.SESSION.CREATED',
    SESSION_REVOKED: 'AUTH.SESSION.REVOKED',
    TWO_FA_ENABLED: 'AUTH.TWO_FA.ENABLED',
    TWO_FA_DISABLED: 'AUTH.TWO_FA.DISABLED',
  },
  ORDER: {
    CREATED: 'ORDER.CREATED',
    UPDATED: 'ORDER.UPDATED',
    CANCELLED: 'ORDER.CANCELLED',
  },
  PAYMENT: {
    INITIATED: 'PAYMENT.INITIATED',
    COMPLETED: 'PAYMENT.COMPLETED',
    FAILED: 'PAYMENT.FAILED',
    REFUNDED: 'PAYMENT.REFUNDED',
  },
};