const PAYMENT_METHODS = Object.freeze({
  COD: 'cod',
  BANK_TRANSFER: 'bank_transfer',
  RAAST: 'raast',
  STRIPE: 'stripe',
  JAZZCASH: 'jazzcash',
  EASYPAISA: 'easypaisa'
});

const SUPPORTED_ORDER_PAYMENT_METHODS = Object.freeze([
  PAYMENT_METHODS.COD,
  PAYMENT_METHODS.BANK_TRANSFER,
  PAYMENT_METHODS.RAAST,
  PAYMENT_METHODS.STRIPE,
  PAYMENT_METHODS.JAZZCASH,
  PAYMENT_METHODS.EASYPAISA
]);

const ORDER_STATUSES = Object.freeze({
  PENDING: 'Pending',
  CONFIRMED: 'Confirmed',
  PROCESSING: 'Processing',
  SHIPPED: 'Shipped',
  DELIVERED: 'Delivered',
  CANCELLED: 'Cancelled'
});

const ORDER_TRANSITIONS = Object.freeze({
  [ORDER_STATUSES.PENDING]: Object.freeze([
    ORDER_STATUSES.CONFIRMED,
    ORDER_STATUSES.CANCELLED
  ]),
  [ORDER_STATUSES.CONFIRMED]: Object.freeze([
    ORDER_STATUSES.PROCESSING,
    ORDER_STATUSES.CANCELLED
  ]),
  [ORDER_STATUSES.PROCESSING]: Object.freeze([
    ORDER_STATUSES.SHIPPED
  ]),
  [ORDER_STATUSES.SHIPPED]: Object.freeze([
    ORDER_STATUSES.DELIVERED
  ]),
  [ORDER_STATUSES.DELIVERED]: Object.freeze([]),
  [ORDER_STATUSES.CANCELLED]: Object.freeze([])
});

const CUSTOMER_CANCELLABLE_STATUSES = Object.freeze([
  ORDER_STATUSES.PENDING,
  ORDER_STATUSES.CONFIRMED
]);

const ORDER_LIMITS = Object.freeze({
  MAX_LINES: 50,
  MAX_QUANTITY_PER_LINE: 20,
  MAX_PAGE_SIZE: 100,
  MAX_TRANSACTION_ATTEMPTS: 3,
  MAX_ORDER_ID_ATTEMPTS: 3
});

module.exports = {
  PAYMENT_METHODS,
  SUPPORTED_ORDER_PAYMENT_METHODS,
  ORDER_STATUSES,
  ORDER_TRANSITIONS,
  CUSTOMER_CANCELLABLE_STATUSES,
  ORDER_LIMITS
};
